#!/usr/bin/env bash

# Once connected, the pulse secure VPN will route the docker network subnet 
# traffic which causes the port forwarding not working.
# This script is used to reset the docker network subnet after connecting to
# the VPN.
#
# The steps are:
# 1. connect to the VPN
# 2. stop/rm all the containers
# 3. run this script

set -euo pipefail

# get the current docker subnet without the mask length
old_subnet=$(docker network inspect bridge | grep Gateway | awk '{print $2}' | sed 's/\"//g' | sed 's/,//g' | cut -d'/' -f1)

# iterate the first three parts of the subnet, use a map to store each part 
# with the index is ith and the value is the part
# TODO(charleszheng44): when the value is smaller than 1, plus 1 but make sure
# it will be smaller than 255
declare -A subnet_parts
for i in {1..3}; do
    subnet_part=$(echo $old_subnet | cut -d'.' -f$i)
    if [ "$subnet_part" -ge 1 ]; then
        subnet_part=$((subnet_part-1))
    fi
    subnet_parts[$i]=$subnet_part
done

# construct the new subnet
new_subnet=${subnet_parts[1]}.${subnet_parts[2]}.${subnet_parts[3]}.${subnet_parts[4]}
printf "converting $old_subnet to $new_subnet\n"
sed -i "s|$old_subnet|$new_subnet|g" /etc/docker/daemon.json
systemctl restart docker
